; This file was auto-generated by drush make (sort of)
core = 7.x

api = 2
projects[drupal][version] = "7.39"

; Modules
projects[admin][subdir] = "contrib"
projects[admin][version] = "2.0-beta3"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[features_extra][subdir] = "contrib"
projects[features_extra][version] = "1.0"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[taxonomy_menu_block][subdir] = "contrib"
projects[taxonomy_menu_block][version] = "1.4"

projects[token][subdir] = "contrib"
projects[token][version] = "1.6"

projects[views][subdir] = "contrib"
projects[views][version] = "3.11"


