l; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.39"

; Modules
projects[admin][version] = "2.0-beta3"
projects[admin][subdir] = "contrib"
projects[ctools][version] = "1.9"
projects[ctools][subdir] = "contrib"
projects[date][version] = "2.9"
projects[date][subdir] = "contrib"
projects[devel][version] = "1.5"
projects[devel][subdir] = "contrib"
projects[features][version] = "1.0"
projects[features][subdir] = "contrib"
projects[features_extra][version] = "1.0"
projects[features_extra][subdir] = "contrib"
projects[field_group][version] = "1.4"
projects[field_group][subdir] = "contrib"
projects[libraries][version] = "2.2"
projects[libraries][subdir] = "contrib"
projects[pathauto][version] = "1.2"
projects[pathauto][subdir] = "contrib"
projects[redirect][version] = "1.0-rc3"
projects[redirect][subdir] = "contrib"
projects[strongarm][version] = "2.0"
projects[strongarm][subdir] = "contrib"
projects[taxonomy_menu_block][version] = "1.4"
projects[taxonomy_menu_block][subdir] = "contrib"
projects[token][version] = "1.6"
projects[token][subdir] = "contrib"
projects[views][version] = "3.11"
projects[views][subdir] = "contrib"

; Themes
projects[rubik][version] = "4.2"
projects[tao][version] = "3.1"

